import { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import {
  ArrowLeft, FileText, BarChart3, Plus,
  GripVertical, X, Eye, Download, Sparkles, AlertTriangle,
  ClipboardCheck, PieChart, Type, BookOpen, ChevronDown,
  Layout, MessageSquare, UserCheck, Users
} from 'lucide-react';
import { WORKFLOWS, EXCEPTION_DATA, ACTION_TAKEN_DATA } from '../../data/mockData';
import { useToast } from '../shared/Toast';

interface Props {
  context: 'new' | 'action-report' | 'from-template' | null;
  onBack: () => void;
}

interface ReportSection {
  id: string;
  type: 'workflow-output' | 'text' | 'chart' | 'exception-summary' | 'action-taken';
  title: string;
  content: string;
}

const AVAILABLE_BLOCKS = [
  { type: 'workflow-output' as const, label: 'Workflow Output', icon: BarChart3, desc: 'Add results from a workflow run' },
  { type: 'text' as const, label: 'Commentary', icon: Type, desc: 'Add text commentary section' },
  { type: 'chart' as const, label: 'Chart / Visualization', icon: PieChart, desc: 'Add a chart block' },
  { type: 'exception-summary' as const, label: 'Exception Summary', icon: AlertTriangle, desc: 'Summary of flagged exceptions' },
  { type: 'action-taken' as const, label: 'Action Taken Summary', icon: ClipboardCheck, desc: 'Risk owner actions and resolutions' },
];

function getInitialSections(context: Props['context']): ReportSection[] {
  if (context === 'action-report') {
    return [
      { id: 's-1', type: 'text', title: 'Executive Summary', content: 'This report summarizes exceptions identified by the Duplicate Invoice Detection workflow (Run #12) and actions taken by assigned risk owners.' },
      { id: 's-2', type: 'exception-summary', title: 'Exception Overview', content: `${EXCEPTION_DATA.length} exceptions flagged` },
      { id: 's-3', type: 'action-taken', title: 'Actions Taken', content: `${ACTION_TAKEN_DATA.length} actions recorded` },
      { id: 's-4', type: 'chart', title: 'Status Breakdown', content: 'Exception resolution status distribution' },
    ];
  }
  return [];
}

const TEMPLATE_CATEGORIES = ['Compliance', 'Risk', 'Controls', 'Analytics', 'Audit', 'Executive'];

export default function ReportBuilder({ context, onBack }: Props) {
  const { addToast } = useToast();
  const [title, setTitle] = useState(context === 'action-report' ? 'Action Taken Report — Duplicate Invoice Detection' : 'Untitled Audit Report');
  const [sections, setSections] = useState<ReportSection[]>(getInitialSections(context));
  const [showPreview, setShowPreview] = useState(false);
  const [dragOverIndex, setDragOverIndex] = useState<number | null>(null);
  const [showWorkflowPicker, setShowWorkflowPicker] = useState(false);
  const [showSaveTemplate, setShowSaveTemplate] = useState(false);
  const [templateName, setTemplateName] = useState('');
  const [templateDesc, setTemplateDesc] = useState('');
  const [templateCategory, setTemplateCategory] = useState('Compliance');
  const [showCategoryDropdown, setShowCategoryDropdown] = useState(false);
  const [templateThemeColor, setTemplateThemeColor] = useState('#6a12cd');
  const [templateHeader, setTemplateHeader] = useState('Confidential — For Internal Use Only');
  const [templateFooter, setTemplateFooter] = useState('Generated by Auditify Copilot');
  const [approvers, setApprovers] = useState([
    { name: 'Tushar Goel', role: 'Audit Manager', status: 'Pending' },
  ]);
  const [showApproverCount, setShowApproverCount] = useState(1);

  const addSection = (type: ReportSection['type']) => {
    if (type === 'workflow-output') {
      setShowWorkflowPicker(true);
      return;
    }
    const titles: Record<string, string> = {
      text: 'Commentary',
      chart: 'Chart / Visualization',
      'exception-summary': 'Exception Summary',
      'action-taken': 'Action Taken Summary',
    };
    setSections(prev => [...prev, {
      id: `s-${Date.now()}`,
      type,
      title: titles[type] || 'New Section',
      content: type === 'exception-summary' ? `${EXCEPTION_DATA.length} exceptions flagged` :
               type === 'action-taken' ? `${ACTION_TAKEN_DATA.length} actions recorded` : '',
    }]);
  };

  const addWorkflowSection = (wf: typeof WORKFLOWS[0]) => {
    setSections(prev => [...prev, {
      id: `s-${Date.now()}`,
      type: 'workflow-output',
      title: `${wf.name} — Output`,
      content: `${wf.runs} runs · Last: ${wf.lastRun} · Type: ${wf.type}`,
    }]);
    setShowWorkflowPicker(false);
  };

  const removeSection = (id: string) => {
    setSections(prev => prev.filter(s => s.id !== id));
  };

  const handleDragStart = (e: React.DragEvent, index: number) => {
    e.dataTransfer.setData('text/plain', String(index));
  };

  const handleDragOver = (e: React.DragEvent, index: number) => {
    e.preventDefault();
    setDragOverIndex(index);
  };

  const handleDrop = (e: React.DragEvent, toIndex: number) => {
    e.preventDefault();
    const fromIndex = parseInt(e.dataTransfer.getData('text/plain'));
    setSections(prev => {
      const next = [...prev];
      const [moved] = next.splice(fromIndex, 1);
      next.splice(toIndex, 0, moved);
      return next;
    });
    setDragOverIndex(null);
  };

  const handleGenerate = () => {
    addToast({ type: 'success', message: 'PDF generated successfully!' });
  };

  const sectionIcon = (type: ReportSection['type']) => {
    const icons = { 'workflow-output': BarChart3, text: Type, chart: PieChart, 'exception-summary': AlertTriangle, 'action-taken': ClipboardCheck };
    const Icon = icons[type];
    return <Icon size={14} />;
  };

  const sectionColor = (type: ReportSection['type']) => {
    const colors = {
      'workflow-output': 'bg-evidence-50 text-evidence-700',
      text: 'bg-paper-50 text-ink-500',
      chart: 'bg-brand-50 text-brand-700',
      'exception-summary': 'bg-high-50 text-high-700',
      'action-taken': 'bg-compliant-50 text-compliant-700',
    };
    return colors[type];
  };

  return (
    <div className="flex h-full bg-surface-2 overflow-hidden">
      {/* Left Sidebar — Available Blocks */}
      <div className="w-[240px] border-r border-border-light bg-white flex flex-col shrink-0">
        <div className="px-4 py-3 border-b border-border-light">
          <h3 className="text-[12px] font-semibold text-text uppercaser">Add Blocks</h3>
        </div>
        <div className="flex-1 overflow-y-auto p-3 space-y-1.5">
          {AVAILABLE_BLOCKS.map(block => (
            <button
              key={block.type}
              onClick={() => addSection(block.type)}
              className="w-full text-left p-3 rounded-xl border border-border-light hover:border-primary/30 hover:bg-primary-xlight/50 hover:shadow-sm transition-all duration-300 cursor-pointer group"
            >
              <div className="flex items-center gap-2 mb-1">
                <div className={`p-1 rounded-md ${sectionColor(block.type)}`}>
                  <block.icon size={12} />
                </div>
                <span className="text-[12px] font-semibold text-text group-hover:text-primary transition-colors">{block.label}</span>
              </div>
              <p className="text-[12px] text-text-muted pl-7">{block.desc}</p>
            </button>
          ))}

          <div className="pt-3 border-t border-border-light mt-3">
            <div className="text-[12px] font-semibold text-text-muted uppercaser mb-2 px-1">Workflows</div>
            {WORKFLOWS.slice(0, 5).map(wf => (
              <button
                key={wf.id}
                onClick={() => addWorkflowSection(wf)}
                className="w-full text-left px-3 py-2 rounded-lg text-[12px] hover:bg-primary-xlight transition-colors cursor-pointer"
              >
                <div className="font-medium text-text truncate">{wf.name}</div>
                <div className="text-[12px] text-text-muted">{wf.type} · {wf.runs} runs</div>
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Main Canvas */}
      <div className="flex-1 flex flex-col min-w-0">
        {/* Top Bar */}
        <div className="h-12 border-b border-border-light bg-white flex items-center justify-between px-5 shrink-0">
          <div className="flex items-center gap-3">
            <button onClick={onBack} className="p-1.5 hover:bg-paper-50 rounded-lg transition-colors cursor-pointer">
              <ArrowLeft size={16} className="text-text-muted" />
            </button>
            <div className="flex items-center gap-2">
              <FileText size={16} className="text-primary" />
              <input
                value={title}
                onChange={e => setTitle(e.target.value)}
                className="text-[14px] font-semibold text-text bg-transparent border-none outline-none focus:underline focus:decoration-primary/30 w-[400px]"
              />
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={() => setShowPreview(p => !p)}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-[12px] font-medium transition-colors cursor-pointer ${
                showPreview ? 'bg-primary/10 text-primary' : 'text-text-secondary hover:bg-paper-50'
              }`}
            >
              <Eye size={13} />
              Preview
            </button>
            <button
              onClick={() => { setTemplateName(title); setShowSaveTemplate(true); }}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-[12px] font-medium text-text-secondary hover:bg-paper-50 transition-colors cursor-pointer"
            >
              <BookOpen size={13} />
              Save as Template
            </button>
            <button
              onClick={handleGenerate}
              className="flex items-center gap-1.5 px-4 py-2 bg-gradient-to-r from-primary to-primary-medium text-white rounded-xl text-[12px] font-semibold hover:from-primary-hover hover:to-primary transition-all cursor-pointer"
            >
              <Download size={13} />
              Generate PDF
            </button>
          </div>
        </div>

        {/* Canvas Area */}
        <div className="flex-1 overflow-y-auto p-6">
          <div className="max-w-3xl mx-auto space-y-3">
            {/* Template Configuration Section */}
            <div className="bg-white rounded-xl border border-border-light shadow-sm p-5 mb-4">
              <h4 className="text-[12px] font-bold text-text-muted uppercaser mb-3 flex items-center gap-2"><Layout size={13} className="text-primary" /> Template Configuration</h4>
              <div className="grid grid-cols-3 gap-4 mb-4">
                <div>
                  <label className="text-[12px] font-semibold text-text block mb-1.5">Template Name</label>
                  <input
                    value={title}
                    onChange={e => setTitle(e.target.value)}
                    className="w-full px-3 py-2 rounded-lg border border-border-light text-[12px] focus:outline-none focus:border-primary/40 focus:ring-2 focus:ring-primary/10"
                  />
                </div>
                <div>
                  <label className="text-[12px] font-semibold text-text block mb-1.5">Theme Color</label>
                  <div className="flex gap-2">
                    {['#6a12cd', '#1a2744', '#0d9488', '#334155', '#dc2626'].map(c => (
                      <button
                        key={c}
                        onClick={() => setTemplateThemeColor(c)}
                        className={`w-8 h-8 rounded-lg border-2 transition-all cursor-pointer ${templateThemeColor === c ? 'border-text scale-110 shadow-md' : 'border-transparent hover:scale-105'}`}
                        style={{ background: c }}
                      />
                    ))}
                  </div>
                </div>
                <div>
                  <label className="text-[12px] font-semibold text-text block mb-1.5">Category</label>
                  <div className="relative">
                    <button
                      onClick={() => setShowCategoryDropdown(p => !p)}
                      className="w-full flex items-center justify-between px-3 py-2 rounded-lg border border-border-light text-[12px] text-text hover:border-primary/30 transition-colors cursor-pointer"
                    >
                      {templateCategory}
                      <ChevronDown size={12} className={`text-text-muted transition-transform ${showCategoryDropdown ? 'rotate-180' : ''}`} />
                    </button>
                  </div>
                </div>
              </div>
              {/* Header / Footer Preview */}
              <div className="grid grid-cols-2 gap-4 mb-3">
                <div>
                  <label className="text-[12px] font-semibold text-text block mb-1.5">Header Text</label>
                  <input value={templateHeader} onChange={e => setTemplateHeader(e.target.value)} className="w-full px-3 py-2 rounded-lg border border-border-light text-[12px] focus:outline-none focus:border-primary/40 focus:ring-2 focus:ring-primary/10" />
                </div>
                <div>
                  <label className="text-[12px] font-semibold text-text block mb-1.5">Footer Text</label>
                  <input value={templateFooter} onChange={e => setTemplateFooter(e.target.value)} className="w-full px-3 py-2 rounded-lg border border-border-light text-[12px] focus:outline-none focus:border-primary/40 focus:ring-2 focus:ring-primary/10" />
                </div>
              </div>
              {/* Mini preview */}
              <div className="border border-border-light rounded-lg p-3 bg-surface-2">
                <div className="bg-white rounded-md shadow-sm border border-border-light overflow-hidden" style={{ aspectRatio: '8.5/3' }}>
                  <div className="h-5 flex items-center justify-between px-3" style={{ background: `${templateThemeColor}10` }}>
                    <span className="text-[6px] font-bold" style={{ color: templateThemeColor }}>{title}</span>
                    <span className="text-[5px] text-text-muted">{templateHeader}</span>
                  </div>
                  <div className="p-2 flex-1">
                    <div className="h-1.5 w-16 bg-text-muted/15 rounded mb-0.5" />
                    <div className="h-1 w-full bg-text-muted/10 rounded mb-0.5" />
                    <div className="h-1 w-3/4 bg-text-muted/10 rounded" />
                  </div>
                  <div className="h-3 bg-surface-2 flex items-center justify-center">
                    <span className="text-[4px] text-text-muted">{templateFooter}</span>
                  </div>
                </div>
              </div>
            </div>

            {/* Content Note */}
            <div className="flex items-center gap-2.5 p-3 bg-primary/[0.03] border border-primary/10 rounded-xl mb-2">
              <div className="p-1.5 rounded-lg bg-primary/10 text-primary shrink-0"><MessageSquare size={13} /></div>
              <p className="text-[12px] text-text-secondary leading-relaxed">
                Report content is added from <strong>/chat</strong> using the "Add to Report" action. Use this builder to configure layout, section ordering, and approval flow.
              </p>
            </div>

            {sections.length === 0 && (
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                className="flex flex-col items-center justify-center py-14 text-center"
              >
                <div className="w-14 h-14 rounded-2xl bg-primary/5 flex items-center justify-center mb-3">
                  <Plus size={24} className="text-primary/40" />
                </div>
                <h4 className="text-[14px] font-semibold text-text mb-1">Add Report Sections</h4>
                <p className="text-[12px] text-text-muted max-w-[300px]">
                  Add blocks from the left sidebar to define your report layout. Drag to reorder sections.
                </p>
              </motion.div>
            )}

            <AnimatePresence>
              {sections.map((section, index) => (
                <motion.div
                  key={section.id}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, scale: 0.95 }}
                >
                <div
                  className={`bg-white rounded-xl border shadow-sm hover:shadow-md hover:border-primary/20 transition-all duration-300 ${
                    dragOverIndex === index ? 'border-primary border-2' : 'border-border-light'
                  }`}
                  draggable
                  onDragStart={e => handleDragStart(e, index)}
                  onDragOver={e => handleDragOver(e, index)}
                  onDrop={e => handleDrop(e, index)}
                  onDragLeave={() => setDragOverIndex(null)}
                >
                  <div className="flex items-center gap-3 px-4 py-3 border-b border-border-light">
                    <div className="cursor-grab active:cursor-grabbing text-text-muted/40 hover:text-text-muted transition-colors">
                      <GripVertical size={14} />
                    </div>
                    <div className={`p-1.5 rounded-lg ${sectionColor(section.type)}`}>
                      {sectionIcon(section.type)}
                    </div>
                    <input
                      value={section.title}
                      onChange={e => setSections(prev => prev.map(s => s.id === section.id ? { ...s, title: e.target.value } : s))}
                      className="flex-1 text-[13px] font-semibold text-text bg-transparent border-none outline-none"
                    />
                    <span className="text-[12px] font-bold uppercaser text-text-muted bg-surface-2 px-2 py-0.5 rounded">
                      {section.type.replace('-', ' ')}
                    </span>
                    <button onClick={() => removeSection(section.id)} className="p-1 hover:bg-risk-50 hover:text-risk-700 rounded text-text-muted transition-colors cursor-pointer">
                      <X size={13} />
                    </button>
                  </div>

                  <div className="px-4 py-3">
                    {section.type === 'text' ? (
                      <div className="flex items-center gap-2 p-3 bg-surface-2 rounded-lg">
                        <MessageSquare size={14} className="text-text-muted shrink-0" />
                        <div>
                          <div className="text-[12px] text-text-muted">Content added from /chat</div>
                          {section.content && <div className="text-[12px] text-text-secondary mt-0.5">{section.content}</div>}
                        </div>
                      </div>
                    ) : section.type === 'workflow-output' ? (
                      <div className="flex items-center gap-3 p-3 bg-surface-2 rounded-lg">
                        <BarChart3 size={16} className="text-evidence-700" />
                        <div>
                          <div className="text-[12px] font-medium text-text">{section.title}</div>
                          <div className="text-[12px] text-text-muted">{section.content}</div>
                        </div>
                      </div>
                    ) : section.type === 'exception-summary' ? (
                      <div className="space-y-2">
                        <div className="flex gap-3">
                          <div className="flex-1 p-2.5 bg-risk-50 rounded-lg text-center">
                            <div className="text-[16px] font-bold text-risk-700">8</div>
                            <div className="text-[12px] text-risk-700 uppercase font-semibold">Flagged</div>
                          </div>
                          <div className="flex-1 p-2.5 bg-high-50 rounded-lg text-center">
                            <div className="text-[16px] font-bold text-high-700">3</div>
                            <div className="text-[12px] text-high-700 uppercase font-semibold">Assigned</div>
                          </div>
                          <div className="flex-1 p-2.5 bg-compliant-50 rounded-lg text-center">
                            <div className="text-[16px] font-bold text-compliant-700">1</div>
                            <div className="text-[12px] text-compliant-700 uppercase font-semibold">Resolved</div>
                          </div>
                        </div>
                        <div className="text-[12px] text-text-muted">Total flagged amount: $616,650</div>
                      </div>
                    ) : section.type === 'action-taken' ? (
                      <div className="overflow-x-auto">
                        <table className="w-full text-[12px]">
                          <thead>
                            <tr className="bg-surface-2">
                              <th className="text-left px-2 py-1.5 font-semibold text-text-secondary">Exception</th>
                              <th className="text-left px-2 py-1.5 font-semibold text-text-secondary">Action By</th>
                              <th className="text-left px-2 py-1.5 font-semibold text-text-secondary">Date</th>
                              <th className="text-left px-2 py-1.5 font-semibold text-text-secondary">Resolution</th>
                            </tr>
                          </thead>
                          <tbody>
                            {ACTION_TAKEN_DATA.map(a => (
                              <tr key={a.exceptionId} className="border-t border-border-light">
                                <td className="px-2 py-1.5 font-mono text-text-muted">{a.exceptionId}</td>
                                <td className="px-2 py-1.5 text-text">{a.actionBy}</td>
                                <td className="px-2 py-1.5 text-text-muted">{a.actionDate}</td>
                                <td className="px-2 py-1.5 text-text">{a.resolution}</td>
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      </div>
                    ) : section.type === 'chart' ? (
                      <div className="flex items-center justify-center h-24 bg-surface-2 rounded-lg">
                        <div className="flex items-end gap-1 h-14">
                          {[40, 65, 25, 80, 55, 70].map((h, i) => (
                            <div key={i} className="w-6 rounded-t" style={{ height: `${h}%`, background: `rgba(106,18,205,${0.15 + (h / 200)})` }} />
                          ))}
                        </div>
                      </div>
                    ) : null}
                  </div>
                </div>
                </motion.div>
              ))}
            </AnimatePresence>

            {/* Approval Chain Section */}
            <div className="bg-white rounded-xl border border-border-light shadow-sm p-5 mt-4">
              <div className="flex items-center justify-between mb-3">
                <h4 className="text-[12px] font-bold text-text-muted uppercaser flex items-center gap-2"><UserCheck size={13} className="text-primary" /> Approval Chain</h4>
                <div className="flex items-center gap-1.5">
                  <span className="text-[12px] text-text-muted">Approvers:</span>
                  <div className="flex gap-1">
                    {[1, 2, 3].map(n => (
                      <button
                        key={n}
                        onClick={() => {
                          setShowApproverCount(n);
                          const APPROVER_DEFAULTS = [
                            { name: 'Tushar Goel', role: 'Audit Manager', status: 'Pending' },
                            { name: 'Deepak Bansal', role: 'Compliance Lead', status: 'Pending' },
                            { name: 'Neha Joshi', role: 'CFO', status: 'Pending' },
                          ];
                          setApprovers(APPROVER_DEFAULTS.slice(0, n));
                        }}
                        className={`w-6 h-6 rounded-md text-[12px] font-bold transition-all cursor-pointer ${showApproverCount === n ? 'bg-primary text-white' : 'bg-surface-2 text-text-muted hover:bg-surface-3'}`}
                      >
                        {n}
                      </button>
                    ))}
                  </div>
                </div>
              </div>
              <div className="space-y-2">
                {approvers.map((approver, i) => (
                  <div key={i} className="flex items-center gap-3 p-3 bg-surface-2 rounded-xl border border-border-light/50">
                    <div className="w-7 h-7 rounded-full bg-primary/10 text-primary text-[12px] font-bold flex items-center justify-center shrink-0">
                      {i + 1}
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2">
                        <input
                          value={approver.name}
                          onChange={e => setApprovers(prev => prev.map((a, idx) => idx === i ? { ...a, name: e.target.value } : a))}
                          className="text-[12px] font-semibold text-text bg-transparent border-none outline-none w-36"
                          placeholder="Approver name"
                        />
                        <input
                          value={approver.role}
                          onChange={e => setApprovers(prev => prev.map((a, idx) => idx === i ? { ...a, role: e.target.value } : a))}
                          className="text-[12px] text-text-muted bg-transparent border-none outline-none flex-1"
                          placeholder="Role"
                        />
                      </div>
                    </div>
                    <span className="text-[12px] font-bold text-mitigated-700 bg-mitigated-50 px-2 py-0.5 rounded-full shrink-0">{approver.status}</span>
                    {i > 0 && i < approvers.length && (
                      <div className="text-[12px] text-text-muted shrink-0">Step {i + 1}</div>
                    )}
                  </div>
                ))}
              </div>
              <div className="mt-3 text-[12px] text-text-muted flex items-center gap-1.5">
                <Users size={11} />
                Report will require approval from {approvers.length} approver{approvers.length > 1 ? 's' : ''} before finalization.
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Save as Template Modal */}
      <AnimatePresence>
        {showSaveTemplate && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-center justify-center"
            onClick={() => setShowSaveTemplate(false)}
          >
            <div className="absolute inset-0 bg-black/20 backdrop-blur-sm" />
            <motion.div
              initial={{ opacity: 0, scale: 0.95, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 20 }}
              className="relative bg-white rounded-2xl shadow-2xl w-[420px] overflow-hidden"
              onClick={e => e.stopPropagation()}
            >
              <div className="px-5 py-4 border-b border-border-light flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <div className="p-1.5 bg-primary/10 text-primary rounded-lg"><BookOpen size={14} /></div>
                  <h4 className="text-[14px] font-semibold text-text">Save as Template</h4>
                </div>
                <button onClick={() => setShowSaveTemplate(false)} className="p-1 hover:bg-paper-50 rounded-lg cursor-pointer">
                  <X size={14} className="text-text-muted" />
                </button>
              </div>
              <div className="p-5 space-y-4">
                <div>
                  <label className="text-[12px] font-semibold text-text mb-1.5 block">Template Name</label>
                  <input
                    value={templateName}
                    onChange={e => setTemplateName(e.target.value)}
                    className="w-full px-3 py-2.5 rounded-xl border border-border-light text-[13px] focus:outline-none focus:border-primary/40 focus:ring-2 focus:ring-primary/10"
                    placeholder="Enter template name"
                  />
                </div>
                <div>
                  <label className="text-[12px] font-semibold text-text mb-1.5 block">Description</label>
                  <textarea
                    value={templateDesc}
                    onChange={e => setTemplateDesc(e.target.value)}
                    className="w-full px-3 py-2.5 rounded-xl border border-border-light text-[13px] focus:outline-none focus:border-primary/40 focus:ring-2 focus:ring-primary/10 resize-none min-h-[70px]"
                    placeholder="Describe what this template is for..."
                  />
                </div>
                <div className="relative">
                  <label className="text-[12px] font-semibold text-text mb-1.5 block">Category</label>
                  <button
                    onClick={() => setShowCategoryDropdown(p => !p)}
                    className="w-full flex items-center justify-between px-3 py-2.5 rounded-xl border border-border-light text-[13px] text-text hover:border-primary/30 transition-colors cursor-pointer"
                  >
                    {templateCategory}
                    <ChevronDown size={14} className={`text-text-muted transition-transform ${showCategoryDropdown ? 'rotate-180' : ''}`} />
                  </button>
                  <AnimatePresence>
                    {showCategoryDropdown && (
                      <motion.div
                        initial={{ opacity: 0, y: -5 }}
                        animate={{ opacity: 1, y: 0 }}
                        exit={{ opacity: 0, y: -5 }}
                        className="absolute left-0 right-0 top-full mt-1 bg-white rounded-xl shadow-xl border border-border-light z-10 overflow-hidden"
                      >
                        {TEMPLATE_CATEGORIES.map(cat => (
                          <button
                            key={cat}
                            onClick={() => { setTemplateCategory(cat); setShowCategoryDropdown(false); }}
                            className={`w-full text-left px-3 py-2 text-[12px] hover:bg-primary-xlight transition-colors cursor-pointer ${templateCategory === cat ? 'text-primary font-semibold bg-primary/5' : 'text-text'}`}
                          >
                            {cat}
                          </button>
                        ))}
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
              </div>
              <div className="px-5 py-4 border-t border-border-light flex justify-end gap-2">
                <button onClick={() => setShowSaveTemplate(false)} className="px-4 py-2 text-[12px] font-medium text-text-secondary hover:bg-paper-50 rounded-lg transition-colors cursor-pointer">Cancel</button>
                <button
                  onClick={() => { addToast({ type: 'success', message: 'Template saved to library!' }); setShowSaveTemplate(false); }}
                  className="px-5 py-2 bg-primary text-white rounded-xl text-[12px] font-semibold hover:bg-primary-hover transition-colors cursor-pointer"
                >
                  Save Template
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Workflow Picker Modal */}
      <AnimatePresence>
        {showWorkflowPicker && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-center justify-center"
            onClick={() => setShowWorkflowPicker(false)}
          >
            <div className="absolute inset-0 bg-black/20 backdrop-blur-sm" />
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="relative bg-white rounded-2xl shadow-xl w-[400px] max-h-[60vh] overflow-hidden"
              onClick={e => e.stopPropagation()}
            >
              <div className="px-4 py-3 border-b border-border-light flex items-center justify-between">
                <h4 className="text-[13px] font-semibold text-text">Add Workflow Output</h4>
                <button onClick={() => setShowWorkflowPicker(false)} className="p-1 hover:bg-paper-50 rounded cursor-pointer">
                  <X size={14} className="text-text-muted" />
                </button>
              </div>
              <div className="overflow-y-auto max-h-[400px] p-2">
                {WORKFLOWS.map(wf => (
                  <button
                    key={wf.id}
                    onClick={() => addWorkflowSection(wf)}
                    className="w-full text-left px-3 py-2.5 rounded-lg hover:bg-primary-xlight transition-colors cursor-pointer"
                  >
                    <div className="flex items-center gap-2">
                      <Sparkles size={12} className="text-primary" />
                      <span className="text-[12px] font-medium text-text">{wf.name}</span>
                    </div>
                    <div className="text-[12px] text-text-muted ml-5 mt-0.5">{wf.type} · {wf.runs} runs · Last: {wf.lastRun}</div>
                  </button>
                ))}
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
